CREATE OR REPLACE FUNCTION getUserByMail(mail IN VARCHAR2)
RETURN SYS_REFCURSOR
IS
user_cursor SYS_REFCURSOR;
BEGIN
OPEN user_cursor FOR
SELECT * FROM USER_ACC WHERE EMAIL = mail;
RETURN user_cursor;
END;
INSERT INTO roles (ACCESS_LEVEL, DESCRIPTION, ROLE_NAME) 
VALUES ('FULL', 'Administrator access', 'ADMIN');

INSERT INTO roles (ACCESS_LEVEL, DESCRIPTION, ROLE_NAME) 
VALUES ('LIMITED', 'Employee access', 'EMPLOYEE');
--call the function
SET SERVEROUTPUT ON
DECLARE
cur SYS_REFCURSOR;
user_row USER_ACC%ROWTYPE;
BEGIN
cur := getUserByMail('qknX3Gn12zLPZcYPD6/on92+AD85wCLx4w6gvj6hcHY=');
LOOP
FETCH cur INTO user_row;
EXIT WHEN cur%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('Email: ' || user_row.EMAIL);
DBMS_OUTPUT.PUT_LINE('Password: ' || user_row.USER_PASSWORD);
END LOOP;
CLOSE cur;
END;
SELECT * FROM USER_ACC WHERE EMAIL = 'qknX3Gn12zLPZcYPD6/on92+AD85wCLx4w6gvj6hcHY=';



