CREATE OR REPLACE FUNCTION getUserByMail(mail IN VARCHAR2)
RETURN SYS_REFCURSOR
IS
user_cursor SYS_REFCURSOR;
BEGIN
OPEN user_cursor FOR
SELECT * FROM USER_ACC WHERE EMAIL = mail;
RETURN user_cursor;
END;
INSERT INTO roles (ACCESS_LEVEL, DESCRIPTION, ROLE_NAME) 
VALUES ('FULL', 'Administrator access', 'ADMIN');

INSERT INTO roles (ACCESS_LEVEL, DESCRIPTION, ROLE_NAME) 
VALUES ('LIMITED', 'Employee access', 'EMPLOYEE');
SELECT *FROM ADMIN;
--call the function
SET SERVEROUTPUT ON
DECLARE
cur SYS_REFCURSOR;
user_row USER_ACC%ROWTYPE;
BEGIN
cur := getUserByMail('qknX3Gn12zLPZcYPD6/on92+AD85wCLx4w6gvj6hcHY=');
LOOP
FETCH cur INTO user_row;
EXIT WHEN cur%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('Email: ' || user_row.EMAIL);
DBMS_OUTPUT.PUT_LINE('Password: ' || user_row.USER_PASSWORD);
END LOOP;
CLOSE cur;
END;
SELECT * FROM USER_ACC WHERE EMAIL = 'qknX3Gn12zLPZcYPD6/on92+AD85wCLx4w6gvj6hcHY=';
DELETE FROM ADMIN WHERE ADMIN_ID = 21;
SELECT *FROM ADMIN;
SELECT *FROM ASSIGNED_ROLES;
INSERT INTO TRAIN_CLASS (CLASS_LETTER, CLASS_NAME, DESCRIPTION) VALUES ('A', 'Freight Locomotive', 'Heavy-duty train for transporting goods');
INSERT INTO TRAIN_CLASS (CLASS_LETTER, CLASS_NAME, DESCRIPTION) VALUES ('B', 'Passenger Train', 'Comfortable train for passenger transport');
INSERT INTO TRAIN_CLASS (CLASS_LETTER, CLASS_NAME, DESCRIPTION) VALUES ('C', 'High-Speed Rail', 'Advanced train for rapid intercity travel');
INSERT INTO TRAIN_CLASS (CLASS_LETTER, CLASS_NAME, DESCRIPTION) VALUES ('D', 'Cargo Wagon', 'Specialized wagon for bulk cargo');

SELECT column_name FROM all_cons_columns 
WHERE constraint_name = 'UK93NJVU4QAXIKWO6805E3T9WS8';

ALTER TABLE TRAIN_TIME
  ADD PLATFORM_ID NUMBER;

ALTER TABLE TRAIN_TIME
ADD CONSTRAINT FK_TRAIN_TIME_PLATFORM
FOREIGN KEY (PLATFORM_ID)
REFERENCES PLATFORM_INFO (PLATFORM_ID);


ALTER TABLE TRAIN_TIME
  ADD TRAIN_ID NUMBER;

ALTER TABLE TRAIN_TIME
ADD CONSTRAINT FK_TRAIN_TIME_TRAIN_ID
FOREIGN KEY (TRAIN_ID)
REFERENCES TRAINS (TRAIN_ID);


ALTER TABLE SEAT_COUNT
  ADD TIME_ID NUMBER;

ALTER TABLE SEAT_COUNT
ADD CONSTRAINT FK_SEAT_COUNT_TIME_ID
FOREIGN KEY (TIME_ID)
REFERENCES TRAIN_TIME (TIME_ID);





